---
name: macos

on: [push, pull_request]

jobs:
  compile:
    name: compile
    runs-on: macos-10.15
    strategy:
      matrix:
        python-version: ['3.6']
        build-version: ["release", "debug"]
    steps:
      - name: clone-repo
        uses: actions/checkout@master

      - name: setup-python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: compile
        run: |
          export CXXFLAGS="-Werror"  # Treat compilation warnings as errors.
          ./build.py ${{ matrix.build-version }}

      - name: upload-planner
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.build-version }}
          path: builds/${{ matrix.build-version }}


  test:
    name: test
    runs-on: macos-10.15
    needs: compile
    strategy:
      matrix:
        python-version: ['3.6']
    steps:
      - name: clone-repo
        uses: actions/checkout@master

      - name: setup-python
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: setup-dependencies
        run: |
          pip3 install tox
          mkdir builds

      - name: download-planner
        uses: actions/download-artifact@master
        with:
          # without 'name' attribute all artifacts are downloaded and the
          # artifact name is used as directory name.
          path: builds/

      - name: test
        run: |
          chmod +x builds/debug/bin/downward
          chmod +x builds/release/bin/downward
          cd misc
          tox -e py,translator,search

...
