---
name: macOS

on: [push, pull_request]

jobs:
  test:
    name: Compile and test planner
    timeout-minutes: 60
    runs-on: macos-10.15
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: 3.6

      - name: Compile planner
        run: |
          export CXXFLAGS="-Werror" # Treat compilation warnings as errors.
          ./build.py
          ./build.py --debug

      - name: Install tox
        run: |
          pip3 install tox

      - name: Run tox tests
        run: |
          cd misc
          tox -e driver,translator,search

...
